name: CI and CD

on:
  push:
    branches:
      - testing_cd

jobs: 
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install
      - run: npm run build
      - run: npm test
      - name: Deploy
        uses: 
crazy-max/ghaction-github-pages
        with:
          target_branch: gh-pages
          build_dir: build
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
